server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest
    username: root
    password: 159753
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
